server:
  port: 8081
  context-path: /test

#数据库postgresql
# DataSource and JPA Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mockitotest?useUnicode\=true&ampcharacterEncoding\=utf-8
    username: postgres
    password: Teamw0rk
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jadira:
        usertype:
          autoRegisterUserTypes: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  thymeleaf:
    cache: false